# Generated by Django 2.1.8 on 2019-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('kinds', models.CharField(choices=[('card', 'card'), ('post', 'post')], max_length=200)),
                ('view_count', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
