# Generated by Django 2.0.13 on 2019-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시간')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너',
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시간')),
                ('image', models.ImageField(upload_to='image/', verbose_name='이미지')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='순서')),
            ],
            options={
                'verbose_name': '게시글 이미지',
                'verbose_name_plural': '게시글 이미지',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시간')),
                ('body', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시간')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('kinds', models.PositiveSmallIntegerField(choices=[(0, 'card'), (1, 'post')], verbose_name='타입')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'basic'), (1, 'sex'), (2, 'news')], verbose_name='카테고리')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='대표이미지')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
            },
        ),
    ]
