# Generated by Django 2.1.8 on 2019-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190710_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('basic', 'basic'), ('emergency', 'emergency'), ('news', 'news')], default='basic', max_length=200),
            preserve_default=False,
        ),
    ]
