# Generated by Django 2.1.8 on 2019-07-24 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190725_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
    ]
