# Generated by Django 2.0.13 on 2019-07-11 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20190712_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardimage',
            options={'verbose_name': '게시글 이미지', 'verbose_name_plural': '게시글 이미지'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 시간'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 시간'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'basic'), (1, 'emergency'), (2, 'news')], verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kinds',
            field=models.PositiveSmallIntegerField(choices=[(0, 'card'), (1, 'post')], verbose_name='타입'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
