# Generated by Django 2.1.8 on 2019-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190712_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'basic'), (1, 'sex'), (2, 'news')], verbose_name='카테고리'),
        ),
    ]
