# Generated by Django 2.0.13 on 2019-07-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190712_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='프로필사진'),
        ),
    ]
