# Generated by Django 2.0.13 on 2019-08-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190807_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': '질문', 'verbose_name_plural': '질문'},
        ),
    ]
