# Generated by Django 2.0.13 on 2019-08-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190807_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
    ]
