# Generated by Django 2.0.13 on 2019-08-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190808_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
    ]
