# Generated by Django 2.0.13 on 2019-08-08 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_auto_20190808_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시간')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Question', verbose_name='질문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '질문 좋아요',
                'verbose_name_plural': '질문 좋아요',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_like_users',
            field=models.ManyToManyField(blank=True, related_name='question_like_users', through='boards.QuestionLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('user', 'question')},
        ),
    ]
