# Generated by Django 2.0.13 on 2019-08-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20190808_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
