# Generated by Django 2.0.13 on 2019-08-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190808_0409'),
        ('boards', '0006_auto_20190809_0246'),
    ]

    operations = [
    ]
